//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} feature is not enabled for this {1}!.
        /// </summary>
        public static string FeatureIsNotEnabled {
            get {
                return ResourceManager.GetString("FeatureIsNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some inconsitency error for this user!.
        /// </summary>
        public static string InconsitencyDataForUser {
            get {
                return ResourceManager.GetString("InconsitencyDataForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some inconsitency error for this user balance!.
        /// </summary>
        public static string InconsitencyDataForUserBalance {
            get {
                return ResourceManager.GetString("InconsitencyDataForUserBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some inconsitency error for this user wallet!.
        /// </summary>
        public static string InconsitencyDataForUserWallet {
            get {
                return ResourceManager.GetString("InconsitencyDataForUserWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not active in this {1}!.
        /// </summary>
        public static string ItemIsNotActiveIn {
            get {
                return ResourceManager.GetString("ItemIsNotActiveIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not any user with this cell phone number!.
        /// </summary>
        public static string NoUserWithThisCellPhoneNumber {
            get {
                return ResourceManager.GetString("NoUserWithThisCellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount value is more than {0} value!.
        /// </summary>
        public static string TheAmountValueIsMore {
            get {
                return ResourceManager.GetString("TheAmountValueIsMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company access to this wallet is not active!.
        /// </summary>
        public static string TheCompanyAccessToThisWalletIsNotActive {
            get {
                return ResourceManager.GetString("TheCompanyAccessToThisWalletIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company does not have access to this wallet!.
        /// </summary>
        public static string TheCompanyDoesNotHaveAccessToThisWallet {
            get {
                return ResourceManager.GetString("TheCompanyDoesNotHaveAccessToThisWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is not active!.
        /// </summary>
        public static string TheItemIsNotActive {
            get {
                return ResourceManager.GetString("TheItemIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is null!.
        /// </summary>
        public static string TheItemIsNull {
            get {
                return ResourceManager.GetString("TheItemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not any {0} with this token!.
        /// </summary>
        public static string ThereIsNotAnyItemWithThisToken {
            get {
                return ResourceManager.GetString("ThereIsNotAnyItemWithThisToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user access to this wallet is not active!.
        /// </summary>
        public static string TheUserAccessToThisWalletIsNotActive {
            get {
                return ResourceManager.GetString("TheUserAccessToThisWalletIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not have access to this wallet!.
        /// </summary>
        public static string TheUserDoesNotHaveAccessToThisWallet {
            get {
                return ResourceManager.GetString("TheUserDoesNotHaveAccessToThisWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server IP {0} is not active for this company!.
        /// </summary>
        public static string ThisIPIsNotActive {
            get {
                return ResourceManager.GetString("ThisIPIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server IP {0} is not defined for this company!.
        /// </summary>
        public static string ThisIPIsNotDefinedForThisCompany {
            get {
                return ResourceManager.GetString("ThisIPIsNotDefinedForThisCompany", resourceCulture);
            }
        }
    }
}
